### ISSUE TITLE
Readme

### ISSUE THREAD

**Issue by cha2hyun** [onesine/react-tailwindcss-select#13]
### https://github.com/onesine/react-tailwindcss-select#formatgrouplabel

Code
```js
const options = [
    {
        label: "Mammal",
        options: [
            { value: "Dolphin", labe: "🐬 Dolphin" },
            { value: "Giraffe", labe: "🦒 Giraffe" }
        ]
    },
    {
        label: "Carnivore",
        options: [
            { value: "Tiger", labe: "🐅 Tiger" },
            { value: "Lion", labe: "🦁 Lion" }
        ]
    }
];

```

The `labe` in option has to be a `label`. It will occurs error below
<img width="1092" alt="image" src="https://user-images.githubusercontent.com/56015532/221117962-34151d6a-cd68-4a79-b1e8-c29b5150ba50.png">

😀

**Comment by onesine** [comment]
Hi @cha2hyun 👋,

I thank you for your feedback. You are right there is indeed a problem with this readme.

Thanks for the MR.
