### ISSUE TITLE
Select field closing for multiple selection

### ISSUE THREAD

**Issue by barbeblanche96** [onesine/react-tailwindcss-select#2]
The select field closes each time an item is selected for multiple selection

**Comment by onesine** [comment]
Thank you for the situation raised. It was a personal choice at first to do it this way. But I think it's appropriate to do it the way you asked.

**Comment by barbeblanche96** [comment]
Nice

**Comment by onesine** [comment]
Co-authored-by: Onesine [philemonlewhe@gmail.com](mailto:philemonlewhe@gmail.com)
