### ISSUE TITLE
Feature Request: Custom Styling of Select

### ISSUE THREAD

**Issue by lyqht** [onesine/react-tailwindcss-select#3]
Hello there! I chanced upon this library while looking for react-select alternatives because of the problem of tailwindcss styles not applying correctly over there (which you also mentioned in this project's README 😆)

I would like a way to style the option component, like how react-select provides a `formatGroupLabel` and `formatOptionLabel`.

**Comment by onesine** [comment]
Thank you for your remark and also for the proposal you ask.

It's very nice to know that other people have the same problem and that this library could help them.

Your remark will be taken into account very soon.

**Comment by mkandan** [comment]
Hey @onesine, were the docs updated with the key that refers to the "Select..." box itself? I've gone through the [keys section](https://github.com/onesine/react-tailwindcss-select#all-keys), but can't seem to find which one controls the box.
![image](https://user-images.githubusercontent.com/40218068/218292758-0a993a91-6030-472b-ad92-f93def412b93.png)

**Comment by Lwachira** [comment]
Co ask, I'm trying to make the input field match my dark mode styles.

**Comment by kengru** [comment]
@mkandan did you found out? Going through the same thing
