### ISSUE TITLE
index.css file doesn't exist in dist

### ISSUE THREAD

**Issue by wcardosodev** [onesine/react-tailwindcss-select#6]
I'm using vite for my application and that doesn't import styling from node modules and following the guide it says there should be an index.css file in the dist folder, however there isn't one and I can't seem to see it in any of the other folders either.

**Comment by onesine** [comment]
You are indeed right, the index.css file is not in the dist directory. I'll fix that. But if you use tailwind in your project, you don't need this CSS file. I can see your tailwindcss.config.js file if you use tailwind.

**Comment by onesine** [comment]
@wcardosodev The index.css file is already available in the dist directory. Upgrade the package to version 1.5.1 to see it.

**Comment by wcardosodev** [comment]
Thank you 👍🏼
