### ISSUE TITLE
Error in Options component

### ISSUE THREAD

**Issue by thobenayann** [onesine/react-tailwindcss-select#8]
Hi there ! First, great job, exactly what we need for a multiselect input 👍

I would like to use your "formatGroupLabel" example but i'm facing an issue when i try to select something by clicking on the input field.

Steps :
- Create a project with npx create-react-app
- Add tailwind CSS and your package
- copy/past your tailwind.config.js options
- copy/past your "formatGroupLabel" example
(I use React 18.2.0)

Now if i run it, and click on the field, the error above occured : 
"Cannot read properties of undefined (reading 'toLowerCase')
    at filterItem (Options.tsx:31:1)
    at Array.filter (<anonymous>)
    at Options.tsx:38:1"
    
Maybe i've miss something !

Thanks

**Comment by onesine** [comment]
Hello @thobenayann 👋

Thanks for your feedback and really sorry for the delay. I think it must be because of the options. There is a typo problem. We have `labe` instead of `label`.

Thanks to @cha2hyun for his PR(#14) which solves the problem
